services:
  backenddiet:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3334:3334"
    environment:
      - NODE_ENV=production
      - API_KEY=${API_KEY}
    restart: unless-stopped
    volumes:
      - ./logs:/usr/src/dietbackend/logs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
